# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
#  exporters:
#    otlphttp/example:
#      endpoint: <your-endpoint-url>
#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlphttp/example]

extensions:
  headers_setter:
    headers:
      - action: insert
        key: X-Scope-OrgID
        value: tenant1

exporters:
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true
    auth:
        authenticator: headers_setter
  otlphttp/loki:
    endpoint: "http://loki-write:3100/otlp"
    tls:
      insecure: true    
    auth:
      authenticator: headers_setter
service:
  extensions: [headers_setter]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [spanmetrics, otlp/tempo, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki, debug]